In [69]:
import pandas as pd
import re
import math
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
import numpy as np

from torch.nn.utils.rnn import pad_sequence
import torch.nn.functional as F

import sentencepiece as spm

from tqdm import tqdm
import random

file = "amazon_review.csv"

data = pd.read_csv(file).dropna(ignore_index=True)
data['overall'] = data["overall"] - 1

vocab_size = 16000
seq_len = 512

spm.SentencePieceTrainer.train(
    input='amazon_reviews.txt',
    model_prefix='amazon_reviews',
    vocab_size=vocab_size,
    model_type='unigram',
    character_coverage=1.0
)

tok = spm.SentencePieceProcessor(model_file='amazon_reviews.model')

filter_ = 1

ls  = [len(tok.encode(i, out_type=int)) for i in data["reviewText"]]

data["lengths"] = ls

data_trunc = data[data["lengths"]<=80]

v = data_trunc["overall"].value_counts()

balanced_data = (
    data_trunc.groupby("overall")
      .sample(n=min(v), random_state=42)
      .reset_index(drop=True)
)

len(balanced_data)

df_shuffled = balanced_data.sample(frac=filter_, random_state=42).reset_index(drop=True)

# Split the shuffled DataFrame
train_size = 0.8
train_df = df_shuffled.sample(frac=train_size, random_state=42).reset_index(drop=True)
test_df = df_shuffled.drop(train_df.index).reset_index(drop=True)

sentencepiece_trainer.cc(78) LOG(INFO) Starts training with : 
trainer_spec {
  input: amazon_reviews.txt
  input_format: 
  model_prefix: amazon_reviews
  model_type: UNIGRAM
  vocab_size: 16000
  self_test_sample_size: 0
  character_coverage: 1
  input_sentence_size: 0
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 4192
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  split_digits: 0
  pretokenization_delimiter: 
  treat_whitespace_as_suffix: 0
  allow_whitespace_only_pieces: 0
  required_chars: 
  byte_fallback: 0
  vocabulary_output_piece_score: 1
  train_extremely_large_corpus: 0
  seed_sentencepieces_file: 
  hard_vocab_limit: 1
  use_all_vocab: 0
  unk_id: 0
  bos_id: 1
  eos_id: 2
  pad_id: -1
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  ⁇ 
  enable_differential_privacy: 0

In [70]:
# get one input output pair with special tokens for later concatenation with other pairs for one sequence under max sequence length
def getEncoding(df, i):
    reviewtext = "Review: "+ df["reviewText"].iloc[i]
    rating = "Rating: " + str(int(df["overall"].iloc[i]))
    #row = [16000] + tok.encode(reviewText, out_type=int) + [16001] + tok.encode([int(df["overall"].iloc[i])], out_type = int)
    row = [16000] + tok.encode(reviewtext, out_type = int) + tok.encode(rating, out_type = int) + [16001]
    return row

def getShiftSeq(df_t, max_seq=1024):
    seqs_x = []
    seqs_y = []
    seqs = []
    c = []
    for i in range(len(df_t)):
        row = getEncoding(train_df, i)
        if len(c) + len(row) > max_seq +1:
            seqs_x.append(c[:-1])
            seqs_y.append(c[1:])
            seqs.append(c)
            c = []
        c.extend(row)
    return seqs_x, seqs_y, seqs

train_seqs_x, train_seqs_y, train_seqs = getShiftSeq(train_df, max_seq=seq_len)
test_seqs_x, test_seqs_y, test_seqs = getShiftSeq(test_df, max_seq=seq_len)

In [71]:
class TokenDatasetB(Dataset):
    def __init__(self, seqs_x, seqs_y):
        self.seqs_x = seqs_x
        self.seqs_y = seqs_y
    
    def __len__(self):
        return len(self.seqs_x)
    
    def __getitem__(self, idx):
        return torch.LongTensor(self.seqs_x[idx]), torch.LongTensor(self.seqs_y[idx])

# Padding collate function for variable length sequences
def collate_fnB(batch):
    seqs_x, seqs_y = zip(*batch)
    lens = [len(s) for s in seqs_x]
    max_len = max(lens)
    
    # Pad sequences
    padded_x = torch.zeros(len(seqs_x), max_len, dtype=torch.long)
    padded_y = torch.zeros(len(seqs_y), max_len, dtype=torch.long)
    
    for i, (x, y) in enumerate(zip(seqs_x, seqs_y)):
        padded_x[i, :len(x)] = x
        padded_y[i, :len(y)] = y
    
    return padded_x, padded_y, torch.LongTensor(lens)

dataset = TokenDatasetB(train_seqs_x, train_seqs_y)
train_loader = DataLoader(dataset, batch_size=5, shuffle=True, collate_fn=collate_fnB)

In [72]:
for batch_idx, (x, y, lengths) in enumerate(train_loader):
    print("bi")
    print(batch_idx)
    print("x")
    print(x)
    print(x.shape)
    print("y")
    print(y)
    print(y.shape)
    print("lengths")
    print(lengths.shape)
    break

lengths[:10]

bi
0
x
tensor([[16000,  7421,   292,  ...,     0,     0,     0],
        [16000,  7421,   292,  ...,     0,     0,     0],
        [16000,  7421,   292,  ..., 13254,   292,   468],
        [16000,  7421,   292,  ...,     0,     0,     0],
        [16000,  7421,   292,  ...,   292,   303,     0]])
torch.Size([5, 508])
y
tensor([[ 7421,   292,     4,  ...,     0,     0,     0],
        [ 7421,   292,    45,  ...,     0,     0,     0],
        [ 7421,   292,   267,  ...,   292,   468, 16001],
        [ 7421,   292,   358,  ...,     0,     0,     0],
        [ 7421,   292,  2131,  ...,   303, 16001,     0]])
torch.Size([5, 508])
lengths
torch.Size([5])


tensor([477, 499, 508, 494, 507])

In [73]:
if torch.cuda.is_available():
    print("CUDA is available!")
    print(f"CUDA device count: {torch.cuda.device_count()}")
    print(f"Current CUDA device name: {torch.cuda.get_device_name(0)}")
    device = 'cuda'
else:
    print("CUDA is not available. PyTorch will use the CPU.")
    device = 'cpu'

CUDA is available!
CUDA device count: 1
Current CUDA device name: NVIDIA GeForce RTX 4080 SUPER


In [261]:
# LSTM Model
class LSTMNextToken(nn.Module):
    def __init__(self, vocab_size, embed_dim=64, hidden_dim=128, num_layers=2, dropout=0.3):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        self.lstm = nn.LSTM(embed_dim, hidden_dim, num_layers, 
                           batch_first=True, dropout=dropout if num_layers > 1 else 0)
        self.dropout = nn.Dropout(dropout)
        self.fc = nn.Linear(hidden_dim, vocab_size)
    
    def forward(self, x, lengths):
        embedded = self.embedding(x)
        
        # Pack padded sequence
        packed = nn.utils.rnn.pack_padded_sequence(
            embedded, lengths.cpu(), batch_first=True, enforce_sorted=False
        )
        
        packed_out, _ = self.lstm(packed)
        
        # Unpack
        output, _ = nn.utils.rnn.pad_packed_sequence(packed_out, batch_first=True)
        
        output = self.dropout(output)
        logits = self.fc(output)
        
        return logits


In [262]:
# Training function
def train_model(model, train_loader, epochs=10, lr=1e-4, device='cuda'):
    model = model.to(device)
    criterion = nn.CrossEntropyLoss(ignore_index=0)  # Ignore padding
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    track_loss = []
    for epoch in range(epochs):
        model.train()
        total_loss = 0

        loader = tqdm(train_loader)
        
        for x, y, lengths in loader:
            x, y = x.to(device), y.to(device)
            lengths = lengths.to(device)
            
            optimizer.zero_grad()
            
            # Forward pass
            logits = model(x, lengths)
            
            # Reshape for loss calculation
            logits = logits.view(-1, logits.size(-1))
            y = y.view(-1)
            
            loss = criterion(logits, y)
            
            # Backward pass
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            
            total_loss += loss.item()
            track_loss.append(loss.item())
            avg_loss = sum(track_loss[-10:]) / 10
            loader.set_postfix(loss=avg_loss)
            del logits
            torch.cuda.empty_cache()
        
        avg_loss = total_loss / len(train_loader)
        print(f'Epoch {epoch+1}/{epochs}, Average Loss: {avg_loss:.4f}')
    
    return model




In [265]:
dataset = TokenDatasetB(train_seqs_x, train_seqs_y)
train_loader = DataLoader(dataset, batch_size=4, shuffle=True, collate_fn=collate_fnB)


# Initialize model (set vocab_size to your tokenizer's vocab size + special tokens)
vocab_size = 16000+2  # Adjust based on your tokenizer
model = LSTMNextToken(vocab_size=vocab_size, embed_dim=512, hidden_dim=768, num_layers=4)

In [266]:
total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params}")

Total parameters: 38611074


In [267]:
# Train
model = train_model(model, train_loader, epochs=20, lr=1e-3)


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.95it/s, loss=5.54]


Epoch 1/20, Average Loss: 5.9544


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.88it/s, loss=4.97]


Epoch 2/20, Average Loss: 5.1573


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.90it/s, loss=4.65]


Epoch 3/20, Average Loss: 4.8368


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.86it/s, loss=4.14]


Epoch 4/20, Average Loss: 4.3503


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.88it/s, loss=3.94]


Epoch 5/20, Average Loss: 4.0113


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.81it/s, loss=3.75]


Epoch 6/20, Average Loss: 3.8169


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.89it/s, loss=3.68]


Epoch 7/20, Average Loss: 3.6691


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.75it/s, loss=3.52]


Epoch 8/20, Average Loss: 3.5488


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.83it/s, loss=3.39]


Epoch 9/20, Average Loss: 3.4449


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.78it/s, loss=3.35]


Epoch 10/20, Average Loss: 3.3494


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.90it/s, loss=3.31]


Epoch 11/20, Average Loss: 3.2643


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.84it/s, loss=3.26]


Epoch 12/20, Average Loss: 3.1841


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.77it/s, loss=3.14]


Epoch 13/20, Average Loss: 3.1084


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.86it/s, loss=3.04]


Epoch 14/20, Average Loss: 3.0374


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.79it/s, loss=2.98]


Epoch 15/20, Average Loss: 2.9738


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.80it/s, loss=2.89]


Epoch 16/20, Average Loss: 2.9118


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.91it/s, loss=2.86]


Epoch 17/20, Average Loss: 2.8517


100%|███████████████████████████████| 264/264 [00:13<00:00, 19.85it/s, loss=2.8]


Epoch 18/20, Average Loss: 2.7954


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.89it/s, loss=2.78]


Epoch 19/20, Average Loss: 2.7440


100%|██████████████████████████████| 264/264 [00:13<00:00, 19.81it/s, loss=2.72]

Epoch 20/20, Average Loss: 2.6935


In [268]:
# get one input output pair with special tokens for later concatenation with other pairs for one sequence under max sequence length
def getEncodingOpen(df, i):
    reviewtext = "Review: "+ df["reviewText"].iloc[i]
    rating = "\n Rating: " 
    #row = [16000] + tok.encode(reviewText, out_type=int) + [16001] + tok.encode([int(df["overall"].iloc[i])], out_type = int)
    row = [16000] + tok.encode(reviewtext, out_type = int) + tok.encode(rating, out_type = int)
    correct_output_rating = int(df["overall"].iloc[i])
    row = torch.LongTensor(row)
    correct_output_rating = torch.LongTensor([correct_output_rating])
    return row, correct_output_rating

In [269]:
k = [345, 23, 44, 99]
kt = torch.tensor(k)

In [270]:
annot = torch.tensor(anno)

/tmp/ipykernel_11637/4078374235.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  annot = torch.tensor(anno)


In [271]:
anno, score = getEncodingOpen(test_df, random.randint(0,len(test_df)))

In [272]:
lens = len(anno)
anno_len = torch.tensor([lens])

# Pad sequences
padded_x = torch.zeros(1, 98, dtype=torch.long)
padded_x[0,:lens] = torch.tensor(anno)

padded_x = padded_x.to(device)
anno_len = anno_len.to(device)

/tmp/ipykernel_11637/1788454296.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  padded_x[0,:lens] = torch.tensor(anno)


In [273]:
out = model(padded_x, anno_len)

In [274]:
out.shape

torch.Size([1, 7, 16002])

In [275]:
tokenout = torch.argmax(out,dim=2)[0]

In [276]:
score

tensor([3])

In [277]:
tokenout

tensor([7421,  292,    4,   78,    3,  292, 3210], device='cuda:0')

In [278]:
tok.decode(tokenout.tolist())

'Review: I small.: 0'

In [279]:
class ICLDataset(Dataset):
    def __init__(self, df, shots, seq_len):
        self.df = df
        self.shots = shots
        self.seq_len = seq_len
    
    def __len__(self):
        return len(self.df)

    def getpre(self, idx, l):
        for _ in range(10):
            ixs = []
            xs = []
            for j in range(self.shots):
                sel = idx
                while(sel==idx):
                    sel = random.randint(0, self.__len__() -1)
                xs.extend(getEncoding(self.df, sel))
            if(len(xs) + l <= seq_len):
                return torch.LongTensor(xs)
        raise ValueError(f"can't fit {self.shots} examples in context")
                
            
    
    def __getitem__(self, idx):
        x, y = getEncodingOpen(self.df, idx)
        l = len(x)
        pre = self.getpre(idx, l)
        icl_x = torch.cat((pre,x))
        return icl_x, y

# Padding collate function for variable length sequences
def collate_fn_icl(batch):
    seqs_x, y = zip(*batch)
    lens = [len(s) for s in seqs_x]
    max_len = max(lens)
    
    # Pad sequences
    padded_x = torch.zeros(len(seqs_x), max_len, dtype=torch.long)
    
    for i, x in enumerate(seqs_x):
        padded_x[i, :len(x)] = x
    
    return padded_x, torch.LongTensor(y), torch.LongTensor(lens)



In [280]:
icl_dataset = ICLDataset(test_df, 0, seq_len)
icl_loader = DataLoader(icl_dataset, batch_size=8, shuffle=True, collate_fn=collate_fn_icl)

for batch_idx, (x, y, lengths) in enumerate(icl_loader):
    print("bi")
    print(batch_idx)
    print("x")
    print(x)
    print(x.shape)
    print("y")
    print(y)
    print(y.shape)
    print("lengths")
    print(lengths.shape)
    break

In [281]:
def israting(s):
    bnk = ["0","1","2","3","4"]
    return s in bnk
def isnum(s):
    bnk = [str(n) for n in range(0,20)]
    return s in bnk

def check_token_list(token_list):
    isratings = 0
    isnums = 0
    for token in token_list:
        isratings += 1 if israting(token) else 0
        isnums += 1 if isnum(token) else 0
    return isratings, isnums

In [282]:
tot = 0
num = 0
ratings = 0
correct = 0
for batch_idx, (x, y, lengths) in enumerate(icl_loader):
    x = x.to(device)
    y = y.to(device)
    lengths = lengths.to(device)
    pred_logits = model(x,lengths)
    pred_tokens = torch.argmax(pred_logits,dim=2)
    pred_tokens = pred_tokens.to('cpu')
    pred_last_token = pred_tokens[:,-1].tolist()
    print(pred_tokens.shape)
    for sequence in pred_tokens:
        seqf = [min(int(to), 15999) for to in sequence]
        print(tok.decode(seqf))
        print()
    pred_scores = [tok.decode([token]) for token in pred_last_token]
    print(pred_scores)
    print(y.tolist())
    tot += len(y)
    for t in range(len(y)):
        correct += 1 if pred_scores[t] == str(y[t]) else 0
    isratings, isnums = check_token_list(pred_scores)
    num += isnums
    ratings += isratings
    torch.cuda.empty_cache()
    break

torch.Size([8, 65])
Review: I have have been a size--4 is have been a. I is is a. I disappointed made. Ratinge comfortable with the purchase. Rating: 3 a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a

Review: I quality are very but they little tight than I expected. I normally they would a in the sizes. They is be been a. Rating is a small. I is too too little tight. I: 2 a a a a a a a a a a a a a a a a a a a a a

Review: I I of the',, on the the the.: 0 a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a

Review: I size are very nice made and but can like they other the the a a to be up. down. I son complaint is have a I same are to. to my other shoes to I' not these same again. this future. Rating: 1 a a a a a a a a a a a a

Review: I fit is a than I' too a comfortable. I: 1 a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a a

Review: I have not know the shoes. I havem not sure t

In [283]:
print("tot: ", tot)
print("num: ", num)
print("ratings: ", ratings)
print("correct: ", correct)

tot:  8
num:  1
ratings:  1
correct:  0
