In [1]:
import pandas as pd
import re
import math
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader
import numpy as np

from torch.nn.utils.rnn import pad_sequence
import torch.nn.functional as F

import sentencepiece as spm

from tqdm import tqdm
import random

file = "amazon_review.csv"

data = pd.read_csv(file).dropna(ignore_index=True)
data['overall'] = data["overall"] - 1

vocab_size = 16000
seq_len = 512
pad_token = 16008

spm.SentencePieceTrainer.train(
    input='amazon_reviews.txt',
    model_prefix='amazon_reviews',
    vocab_size=vocab_size,
    model_type='unigram',
    character_coverage=1.0
)

tok = spm.SentencePieceProcessor(model_file='amazon_reviews.model')

filter_ = 1

ls  = [len(tok.encode(i, out_type=int)) for i in data["reviewText"]]

data["lengths"] = ls

data_trunc = data[data["lengths"]<=40]

v = data_trunc["overall"].value_counts()

balanced_data = (
    data_trunc.groupby("overall")
      .sample(n=min(v), random_state=42)
      .reset_index(drop=True)
)

len(balanced_data)

df_shuffled = balanced_data.sample(frac=filter_, random_state=42).reset_index(drop=True)

# Split the shuffled DataFrame
train_size = 0.8
train_df = df_shuffled.sample(frac=train_size, random_state=42).reset_index(drop=True)
test_df = df_shuffled.drop(train_df.index).reset_index(drop=True)

sentencepiece_trainer.cc(78) LOG(INFO) Starts training with : 
trainer_spec {
  input: amazon_reviews.txt
  input_format: 
  model_prefix: amazon_reviews
  model_type: UNIGRAM
  vocab_size: 16000
  self_test_sample_size: 0
  character_coverage: 1
  input_sentence_size: 0
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 4192
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  split_digits: 0
  pretokenization_delimiter: 
  treat_whitespace_as_suffix: 0
  allow_whitespace_only_pieces: 0
  required_chars: 
  byte_fallback: 0
  vocabulary_output_piece_score: 1
  train_extremely_large_corpus: 0
  seed_sentencepieces_file: 
  hard_vocab_limit: 1
  use_all_vocab: 0
  unk_id: 0
  bos_id: 1
  eos_id: 2
  pad_id: -1
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  ⁇ 
  enable_differential_privacy: 0

In [2]:
print("len train df: ", len(train_df))
print("len test df: ", len(test_df))

len train df:  11368
len test df:  2842


In [3]:
torch.cuda.empty_cache()

In [4]:
# get one input output pair with special tokens for later concatenation with other pairs for one sequence under max sequence length
def getEncodingOpen(df, i):
    reviewtext = "Review: "+ df["reviewText"].iloc[i]
    rating = "Rating: " 
    #row = [16000] + tok.encode(reviewText, out_type=int) + [16001] + tok.encode([int(df["overall"].iloc[i])], out_type = int)
    row = [16000] + tok.encode(reviewtext, out_type = int) + [16002] + tok.encode(rating, out_type = int)
    correct_output_rating = int(df["overall"].iloc[i])
    row = torch.LongTensor(row)
    correct_output_rating = torch.LongTensor([correct_output_rating])
    return row, correct_output_rating
# get one input output pair with special tokens for later concatenation with other pairs for one sequence under max sequence length
def getEncoding(df, i):
    reviewtext = "Review: "+ df["reviewText"].iloc[i]
    rating = "Rating: " #+ str(int(df["overall"].iloc[i]))
    score = int(df["overall"].iloc[i])
    row = [16000] + tok.encode(reviewtext, out_type = int) + [16002] + tok.encode(rating, out_type = int) +[score+16003]+ [16001]
    return row


In [5]:
d = {16000: "<BOS>", 16001: "<EOS>",16002: "<SEP>",16003: "<0>",16004: "<1>",16005: "<2>",16006: "<3>",16007: "<4>", 16008: "PAD"}

def decode_seq(seq):
    outp = ""
    sofar = []
    for i in seq:
        if(i<=15999):
            sofar.append(i)
        else:
            outp += tok.decode(sofar)
            outp += d[i]
            sofar = []
    outp += tok.decode(sofar)
    return outp


In [6]:
decode_seq(getEncoding(train_df, 2))

'<BOS>Review: deception is written that a lot of cotton and it is very little one synthetics. Instead of the declared 65 percent of 35 percent. unpleasant for such deception<SEP>Rating:<0><EOS>'

In [7]:
train_df["overall"].iloc[2]

np.float64(0.0)

In [8]:
print(seq_len)

512


In [9]:
def getShiftSeq(df_t, max_seq=1024):
    seqs_x = []
    seqs_y = []
    seqs = []
    c = []
    for i in range(len(df_t)):
        row = getEncoding(df_t, i)
        if len(c) + len(row) > max_seq +1:
            seqs_x.append(c[:-1])
            seqs_y.append(c[1:])
            seqs.append(c)
            c = []
        c.extend(row)
    return seqs_x, seqs_y, seqs

train_seqs_x, train_seqs_y, train_seqs = getShiftSeq(train_df, max_seq=seq_len)
test_seqs_x, test_seqs_y, test_seqs = getShiftSeq(test_df, max_seq=seq_len)

In [10]:
len(train_seqs_x[0])

509

In [11]:
len(train_seqs[0])

510

In [12]:
decode_seq(train_seqs[0][-15:])

'love the shoes but I ordered the wrong size!<SEP>Rating:<3><EOS>'

In [13]:
train_seqs_x[0][-15:]

[4, 68, 5, 44, 23, 4, 88, 5, 346, 30, 34, 16002, 13254, 292, 16006]

In [14]:
train_seqs[0][-15:]

[68, 5, 44, 23, 4, 88, 5, 346, 30, 34, 16002, 13254, 292, 16006, 16001]

In [15]:
class TokenDatasetB(Dataset):
    def __init__(self, seqs_x, seqs_y):
        self.seqs_x = seqs_x
        self.seqs_y = seqs_y
    
    def __len__(self):
        return len(self.seqs_x)
    
    def __getitem__(self, idx):
        return torch.LongTensor(self.seqs_x[idx]), torch.LongTensor(self.seqs_y[idx])

# Padding collate function for variable length sequences
def collate_fnB(batch):
    seqs_x, seqs_y = zip(*batch)
    lens = [len(s) for s in seqs_x]
    max_len = max(lens)
    
    # Pad sequences
    padded_x = torch.zeros(len(seqs_x), max_len, dtype=torch.long) + pad_token
    padded_y = torch.zeros(len(seqs_y), max_len, dtype=torch.long) + pad_token
    
    for i, (x, y) in enumerate(zip(seqs_x, seqs_y)):
        padded_x[i, :len(x)] = x
        padded_y[i, :len(y)] = y
    
    return padded_x, padded_y, torch.LongTensor(lens)

dataset = TokenDatasetB(train_seqs_x, train_seqs_y)
train_loader = DataLoader(dataset, batch_size=50, shuffle=True, collate_fn=collate_fnB)

In [16]:
for batch_idx, (x, y, lengths) in enumerate(train_loader):
    print("bi")
    print(batch_idx)
    print("x")
    print(x.shape)
    xl = x[0].tolist()
    print(xl)
    print()
    
    
    print(decode_seq(x[0].tolist()))
    print()
    print(decode_seq(x[1].tolist()))
    print()
    print(decode_seq(x[2].tolist()))
    print()
    print(decode_seq(x[3].tolist()))
    print()
    print(decode_seq(x[4].tolist()))
    print()
    print("y")
    print(y)
    print(y.shape)
    print("lengths")
    print(lengths.shape)
    break

bi
0
x
torch.Size([5, 506])
[16000, 7421, 292, 1618, 5, 442, 23, 14, 33, 53, 371, 16, 5, 462, 7, 8, 199, 30, 33, 36, 696, 3, 662, 9, 91, 200, 208, 3, 16002, 13254, 292, 16005, 16001, 16000, 7421, 292, 129, 69, 36, 91, 192, 98, 208, 67, 196, 17, 896, 158, 3, 129, 27, 179, 24, 479, 11, 101, 7, 69, 36, 670, 3, 16002, 13254, 292, 16007, 16001, 16000, 7421, 292, 70, 10, 15, 8, 82, 148, 23, 4, 88, 8, 156, 838, 25, 14, 69, 1022, 18, 615, 3, 70, 275, 36, 3, 4, 107, 6701, 10, 7, 4726, 3369, 3, 16002, 13254, 292, 16005, 16001, 16000, 7421, 292, 255, 985, 11, 5, 89, 6, 5232, 15, 19, 74, 184, 3, 16002, 13254, 292, 16006, 16001, 16000, 7421, 292, 181, 148, 11, 556, 526, 16002, 13254, 292, 16005, 16001, 16000, 7421, 292, 1110, 78, 146, 43, 8, 11065, 15580, 79, 3, 16002, 13254, 292, 16004, 16001, 16000, 7421, 292, 4, 88, 8, 2803, 4, 41, 8, 1310, 16, 454, 10, 15, 7, 22, 63, 53, 117, 34, 4, 242, 10, 108, 88, 8, 4229, 16002, 13254, 292, 16005, 16001, 16000, 7421, 292, 606, 244, 9, 209, 28, 79, 3, 5892, 

In [17]:
if torch.cuda.is_available():
    print("CUDA is available!")
    print(f"CUDA device count: {torch.cuda.device_count()}")
    print(f"Current CUDA device name: {torch.cuda.get_device_name(0)}")
    device = 'cuda'
else:
    print("CUDA is not available. PyTorch will use the CPU.")
    device = 'cpu'

CUDA is available!
CUDA device count: 1
Current CUDA device name: NVIDIA GeForce RTX 4080 SUPER


In [18]:

def save_checkpoint(model, optimizer, step, path):
    ckpt = {
        "model": model.state_dict(),
        "optimizer": optimizer.state_dict(),
        "step": step,
    }
    torch.save(ckpt, path)


In [30]:
# LSTM Model
class LSTMNextToken(nn.Module):
    def __init__(self, vocab_size, embed_dim=512, hidden_dim=1024, num_layers=2, dropout=0.2):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embed_dim, padding_idx=0)
        self.lstm = nn.LSTM(embed_dim, hidden_dim, num_layers, 
                           batch_first=True, dropout=dropout if num_layers > 1 else 0)
        self.dropout = nn.Dropout(dropout)
        self.fc = nn.Linear(hidden_dim, vocab_size)
    
    def forward(self, x, lengths):
        embedded = self.embedding(x)
        
        # Pack padded sequence
        packed = nn.utils.rnn.pack_padded_sequence(
            embedded, lengths.cpu(), batch_first=True, enforce_sorted=False
        )
        
        packed_out, _ = self.lstm(packed)
        
        # Unpack
        output, _ = nn.utils.rnn.pad_packed_sequence(packed_out, batch_first=True)
        
        output = self.dropout(output)
        logits = self.fc(output)
        
        return logits


In [31]:
len(train_loader)

24

In [32]:
# Training function
def train_model(model, train_loader, epochs=10, lr=1e-4, device='cuda'):
    model = model.to(device)
    criterion = nn.CrossEntropyLoss(ignore_index=0)  # Ignore padding
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    track_loss = []
    global_step = 0
    for epoch in range(epochs):
        model.train()
        total_loss = 0

        loader = tqdm(train_loader)
        
        for x, y, lengths in loader:
            x, y = x.to(device), y.to(device)
            lengths = lengths.to(device)
            
            optimizer.zero_grad()
            
            # Forward pass
            logits = model(x, lengths)
            
            # Reshape for loss calculation
            logits = logits.view(-1, logits.size(-1))
            y = y.view(-1)
            
            loss = criterion(logits, y)
            
            # Backward pass
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            
            total_loss += loss.item()
            track_loss.append(loss.item())
            avg_loss = sum(track_loss[-10:]) / 10
            loader.set_postfix(loss=avg_loss)
            del logits
            torch.cuda.empty_cache()
            global_step+=1

            ckpt_path = f"ckpt_{epoch}.pt"
            if global_step % 2500 == 0:
                save_checkpoint(model, optimizer, global_step, ckpt_path)
                print(f"Saved checkpoint at step {global_step}")
        
        avg_loss = total_loss / len(train_loader)
        print(f'Epoch {epoch+1}/{epochs}, Average Loss: {avg_loss:.4f}')
    
    return model




In [86]:
dataset = TokenDatasetB(train_seqs_x, train_seqs_y)
train_loader = DataLoader(dataset, batch_size=12, shuffle=True, collate_fn=collate_fnB)


# Initialize model (set vocab_size to your tokenizer's vocab size + special tokens)
vocab_size = 16000+9  # Adjust based on your tokenizer
model = LSTMNextToken(vocab_size=vocab_size,  num_layers=12)

In [87]:
total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params}")

Total parameters: 123270281


In [88]:
# Train
model = train_model(model, train_loader, epochs=20, lr=1e-4)


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.75it/s, loss=5.77]


Epoch 1/20, Average Loss: 7.2164


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.77it/s, loss=5.73]


Epoch 2/20, Average Loss: 5.7165


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.77it/s, loss=5.68]


Epoch 3/20, Average Loss: 5.6892


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.76it/s, loss=5.66]


Epoch 4/20, Average Loss: 5.6803


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.77it/s, loss=5.65]


Epoch 5/20, Average Loss: 5.6701


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.76it/s, loss=5.67]


Epoch 6/20, Average Loss: 5.6704


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.77it/s, loss=5.65]


Epoch 7/20, Average Loss: 5.6654


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.78it/s, loss=5.64]


Epoch 8/20, Average Loss: 5.6621


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.77it/s, loss=5.66]


Epoch 9/20, Average Loss: 5.6613


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.76it/s, loss=5.69]


Epoch 10/20, Average Loss: 5.6606


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.76it/s, loss=5.68]


Epoch 11/20, Average Loss: 5.6548


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.76it/s, loss=5.66]


Epoch 12/20, Average Loss: 5.6557


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.76it/s, loss=5.65]


Epoch 13/20, Average Loss: 5.6518


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.76it/s, loss=5.64]


Epoch 14/20, Average Loss: 5.6506


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.76it/s, loss=5.65]


Epoch 15/20, Average Loss: 5.6475


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.75it/s, loss=5.63]


Epoch 16/20, Average Loss: 5.6458


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.78it/s, loss=5.65]


Epoch 17/20, Average Loss: 5.6467


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.74it/s, loss=5.64]


Epoch 18/20, Average Loss: 5.6462


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.76it/s, loss=5.66]


Epoch 19/20, Average Loss: 5.6438


100%|████████████████████████████████| 48/48 [00:17<00:00,  2.77it/s, loss=5.63]

Epoch 20/20, Average Loss: 5.6404


In [36]:
model.eval()

LSTMNextToken(
  (embedding): Embedding(16009, 512, padding_idx=0)
  (lstm): LSTM(512, 1024, num_layers=12, batch_first=True, dropout=0.2)
  (dropout): Dropout(p=0.2, inplace=False)
  (fc): Linear(in_features=1024, out_features=16009, bias=True)
)

In [37]:
k = [345, 23, 44, 99]
kt = torch.tensor(k)

In [38]:
seq_len

512

In [39]:
anno, score = getEncodingOpen(test_df, random.randint(0,len(test_df)))

In [40]:
annot = torch.tensor(anno)

/tmp/ipykernel_62526/4078374235.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  annot = torch.tensor(anno)


In [41]:
decode_seq(anno.tolist())

'<BOS>Review: Did not fit<SEP>Rating:'

In [42]:
annot

tensor([16000,  7421,   292,  1480,    36,    26, 16002, 13254,   292])

In [43]:
score

tensor([0])

In [44]:
lens = len(anno)
anno_len = torch.tensor([lens])

# Pad sequences
padded_x = torch.zeros(1, 512, dtype=torch.long) + pad_token
padded_x[0,:lens] = torch.tensor(anno)

padded_x = padded_x.to(device)
anno_len = anno_len.to(device)

/tmp/ipykernel_62526/1037303179.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  padded_x[0,:lens] = torch.tensor(anno)


In [45]:
padded_x[0].shape

torch.Size([512])

In [54]:
anno_len

tensor([9], device='cuda:0')

In [46]:
decode_seq(padded_x[0].tolist())

'<BOS>Review: Did not fit<SEP>Rating:PADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPAD

In [47]:
out = model(padded_x, anno_len)

In [48]:
out.shape

torch.Size([1, 9, 16009])

In [49]:
tokenout = torch.argmax(out,dim=2)[0]

In [50]:
score

tensor([0])

In [51]:
tokenout.shape

torch.Size([9])

In [52]:
decode_seq(tokenout.tolist())

'Review::::::::'

In [55]:
def predict_label_ids(model, x, pad_token, anno_len):
    model.eval()
    with torch.no_grad():
        logits = model(x, anno_len)                    # (B, T, V)
        nonpad_len = (x != pad_token).sum(dim=1)   # (B,)
        last_pos = nonpad_len - 1
        last_logits = logits[torch.arange(x.size(0)), last_pos]   # (B, V)
        probs = last_logits.softmax(dim=-1)
        top5 = probs.topk(5, dim=-1)
        top1 = probs.topk(1, dim = -1)
        return top5, probs[:, 16003:16008], top1   # top5 and probs specifically for label tokens

# Example:
#x = torch.LongTensor([padded_x]).to(device)
top5, label_probs, top1 = predict_label_ids(model, padded_x, pad_token, anno_len)
print("label_probs:", label_probs.cpu().numpy())
print("top5 ids:", top5.indices.cpu().numpy())
print("top1 ids:", top1.indices.cpu().numpy())

label_probs: [[0.00684289 0.00620727 0.00698792 0.00641123 0.00813268]]
top5 ids: [[  292     3  7421 16002 13254]]
top1 ids: [[292]]


In [62]:
decode_seq(top1[1].tolist()[0]), score.item()

(':', 0)

In [63]:
class ICLDataset(Dataset):
    def __init__(self, df, shots, seq_len):
        self.df = df
        self.shots = shots
        self.seq_len = seq_len
    
    def __len__(self):
        return len(self.df)

    def getpre(self, idx, l):
        for _ in range(10):
            ixs = []
            xs = []
            for j in range(self.shots):
                sel = idx
                while(sel==idx):
                    sel = random.randint(0, self.__len__() -1)
                xs.extend(getEncoding(self.df, sel))
            if(len(xs) + l <= seq_len):
                return torch.LongTensor(xs)
        raise ValueError(f"can't fit {self.shots} examples in context")
                
            
    
    def __getitem__(self, idx):
        x, y = getEncodingOpen(self.df, idx)
        l = len(x)
        pre = self.getpre(idx, l)
        icl_x = torch.cat((pre,x))
        return icl_x, y

# Padding collate function for variable length sequences
def collate_fn_icl(batch):
    seqs_x, y = zip(*batch)
    lens = [len(s) for s in seqs_x]
    max_len = max(lens)
    
    # Pad sequences
    padded_x = torch.zeros(len(seqs_x), max_len, dtype=torch.long) + pad_token
    
    for i, x in enumerate(seqs_x):
        padded_x[i, :len(x)] = x
    
    return padded_x, torch.LongTensor(y), torch.LongTensor(lens)



In [64]:
icl_dataset = ICLDataset(train_df, 0, seq_len)
icl_loader = DataLoader(icl_dataset, batch_size=8, shuffle=True, collate_fn=collate_fn_icl)

In [65]:
for batch_idx, (x, y, lengths) in enumerate(icl_loader):
    print("bi")
    print(batch_idx)
    print("x")
    print(x.shape)
    xl = x[0].tolist()
    print(xl)
    print()
    
    
    print(decode_seq(xl))
    print("y")
    print(y)
    print(y.shape)
    print("lengths")
    print(lengths.shape)
    break

bi
0
x
torch.Size([8, 45])
[16000, 7421, 292, 2491, 894, 1048, 974, 373, 3, 16002, 13254, 292, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008]

<BOS>Review: Band broke within four months.<SEP>Rating:PADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPAD
y
tensor([2, 1, 1, 1, 4, 2, 0, 2])
torch.Size([8])
lengths
torch.Size([8])


In [66]:
def israting(s):
    bnk = ["0","1","2","3","4"]
    return s in bnk
def isnum(s):
    bnk = [str(n) for n in range(0,20)]
    return s in bnk

def check_token_list(token_list):
    isratings = 0
    isnums = 0
    for token in token_list:
        isratings += 1 if israting(token) else 0
        isnums += 1 if isnum(token) else 0
    return isratings, isnums

In [67]:
d

{16000: '<BOS>',
 16001: '<EOS>',
 16002: '<SEP>',
 16003: '<0>',
 16004: '<1>',
 16005: '<2>',
 16006: '<3>',
 16007: '<4>',
 16008: 'PAD'}

In [68]:
def get_score(x):
    x = x.tolist()
    for i in range(len(x)-1,0, -1):
        if 16003<= x[i] <=16007:
            return x[i]
    return 20000


In [69]:
test_ex = torch.tensor([ 7421,   292,     4,     6,   945,    35,   161,    19,    31,   161,
             6,    18,   161,    19,    10,    29,    26,   143,   204,     3,
            28,   321,    14,   143,    75,   460, 13254,   292, 16000, 16008,
         16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008,
         16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008,
         16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008,
         16008])
vv = get_score(test_ex)

In [70]:
vv

20000

In [71]:
def getTokenScore(t):
    if(t==20000):
        return '-'
    return d[t][1]

In [72]:
icl_dataset = ICLDataset(train_df, 0, seq_len)
icl_loader = DataLoader(icl_dataset, batch_size=8, shuffle=True, collate_fn=collate_fn_icl)

In [73]:
tot = 0
num = 0
ratings = 0
correct = 0
for batch_idx, (x, y, lengths) in enumerate(icl_loader):
    x = x.to(device)
    y = y.to(device)
    lengths = lengths.to(device)
    pred_logits = model(x,lengths)
    print(x.shape)
    print(x[0])
    for sequence in x:
        print(decode_seq(sequence.tolist()))
        print()
    print("========================")
    pred_tokens = torch.argmax(pred_logits,dim=2)
    pred_tokens = pred_tokens.to('cpu')
    #pred_tokens = trim_tail(pred_tokens, pad_token)
    #pred_last_token = pred_tokens[:,-1].tolist()
    pred_last_token = [get_score(i) for i in pred_tokens]
    for sequence in pred_tokens:
        print(decode_seq(sequence.tolist()))
        print()
    pred_scores = []
    print(pred_last_token)
    for token in pred_last_token:
        if(token<=15999):
            pred_scores.append(tok.decode([token]))
        else:
            pred_scores.append(getTokenScore(token))

    print('---')
    print(pred_scores)
    
    ys = [str(ans) for ans in y.tolist()]
    print(ys)
    tot += len(y)
    for t in range(len(y)):
        correct += 1 if pred_scores[t] == ys[t] else 0
    isratings, isnums = check_token_list(pred_scores)
    num += isnums
    ratings += isratings
    torch.cuda.empty_cache()
    break

torch.Size([8, 40])
tensor([16000,  7421,   292,  1822,     9,    31,   208,     3,   588,   787,
         4163,    26,    13,    47,    23,   660,    10,    29,   102,  1607,
           16,    21,   406,     3, 16002, 13254,   292, 16008, 16008, 16008,
        16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008, 16008],
       device='cuda:0')
<BOS>Review: New to this brand. Initial fit is good but haven't really walked in them yet.<SEP>Rating:PADPADPADPADPADPADPADPADPADPADPADPADPAD

<BOS>Review: Don't waste money. Tore apart after first use. Very poor quality of material. The color is not black if you order barely black. It came as grey<SEP>Rating:

<BOS>Review: Very well made and sized just right. Looks great in use.<SEP>Rating:PADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPAD

<BOS>Review: poor quality<SEP>Rating:PADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPADPAD

<BOS>Review: A full size too large<SEP>Rating:PAD

In [74]:
print("tot: ", tot)
print("num: ", num)
print("ratings: ", ratings)
print("correct: ", correct)

tot:  8
num:  0
ratings:  0
correct:  0


In [75]:
icl_dataset = ICLDataset(test_df, 2, seq_len)
icl_loader = DataLoader(icl_dataset, batch_size=8, shuffle=True, collate_fn=collate_fn_icl)

In [76]:
tot = 0
num = 0
ratings = 0
correct = 0
for batch_idx, (x, y, lengths) in enumerate(icl_loader):
    x = x.to(device)
    y = y.to(device)
    lengths = lengths.to(device)
    pred_logits = model(x,lengths)
    #print(x.shape)
    #print(x[0])
    #for sequence in x:
    #    print(decode_seq(sequence.tolist()))
    #    print()
    #print("========================")
    pred_tokens = torch.argmax(pred_logits,dim=2)
    pred_tokens = pred_tokens.to('cpu')
    #pred_tokens = trim_tail(pred_tokens, pad_token)
    #pred_last_token = pred_tokens[:,-1].tolist()
    pred_last_token = [get_score(i) for i in pred_tokens]
    #for sequence in pred_tokens:
    #    print(decode_seq(sequence.tolist()))
    #    print()
    pred_scores = []
    #print(pred_last_token)
    for token in pred_last_token:
        if(token<=15999):
            pred_scores.append(tok.decode([token]))
        else:
            pred_scores.append(getTokenScore(token))

    #print('---')
    #print(pred_scores)
    
    ys = [str(ans) for ans in y.tolist()]
    #print(ys)
    tot += len(y)
    for t in range(len(y)):
        correct += 1 if pred_scores[t] == ys[t] else 0
    isratings, isnums = check_token_list(pred_scores)
    num += isnums
    ratings += isratings
    torch.cuda.empty_cache()

In [78]:
print("tot: ", tot)
print("num: ", num)
print("ratings: ", ratings)
print("correct: ", correct)
print("acc: ", correct/tot)

tot:  2842
num:  0
ratings:  0
correct:  0
acc:  0.0


In [ ]:
 4778 / 15396